"""Build the local ATT&CK module from an official STIX bundle; no runtime requests."""
import argparse, hashlib, json, pathlib
p=argparse.ArgumentParser();p.add_argument('bundle');p.add_argument('--output',default='src/attack-catalog.js');a=p.parse_args()
raw=pathlib.Path(a.bundle).read_bytes();bundle=json.loads(raw)
objects=bundle['objects']; collections=[o for o in objects if o.get('type')=='x-mitre-collection']
techniques=[]
for o in objects:
 if o.get('type')!='attack-pattern' or o.get('revoked') or o.get('x_mitre_deprecated'):continue
 ref=next((r for r in o.get('external_references',[]) if r.get('source_name')=='mitre-attack' and r.get('external_id','').startswith('T')),None)
 if not ref:continue
 techniques.append(dict(id=ref['external_id'],name=o['name'],url=ref['url'],platforms=o.get('x_mitre_platforms',[]),tactics=[x['phase_name'] for x in o.get('kill_chain_phases',[]) if x['kill_chain_name']=='mitre-attack'],subtechnique=o.get('x_mitre_is_subtechnique',False)))
techniques.sort(key=lambda x:x['id'])
if len(techniques)<500 or len({x['id'] for x in techniques})!=len(techniques):raise ValueError('Incomplete or duplicate taxonomy')
meta=dict(source='https://github.com/mitre-attack/attack-stix-data',version=collections[0].get('x_mitre_version','unknown') if collections else 'unknown',bundleSha256=hashlib.sha256(raw).hexdigest(),count=len(techniques))
pathlib.Path(a.output).write_text('/* MITRE ATT&CK data. See THIRD_PARTY_NOTICES.md. Generated by scripts/import-attack.py. */\nexport const catalogMeta = '+json.dumps(meta)+';\nexport const techniques = '+json.dumps(techniques,separators=(',',':'))+';\n')
print(json.dumps(meta))
